from .matlab_compat import ifreq_swap, matlab_1b_to_python_0b
from .metrics import divide_with_nan, gaussian_kernel_1d, smooth_last_axis
from .interim_io import (
    SavedRatemapPack,
    load_saved_ratemap_pack,
    load_traj_condition_names,
    subset_saved_ratemap_pack_cells,
)
from .cell_classification import (
    filter_cell_ids_by_pred_type,
    load_cell_classification_table,
)
from .cue_zones import (
    CueZoneLayout,
    complement_spans,
    cue_zone_layout_for_condition,
    label_xbin_centers_by_zone,
    label_xbin_centers_by_zone_component,
    zone_component_names_for_layout,
)
from .bootstrap import (
    NullBootstrapConfig,
    empirical_pval_cx,
    empirical_pval_tx,
    simulate_null_fr_s_txrep,
)
from .ssi import (
    compute_condition_occupancy,
    empirical_pvalue_from_null,
    spatial_selectivity_index,
    spatial_selectivity_index_reps,
    ssi_null_by_condition,
    ssi_observed_by_condition,
)
from .pipeline import (
    RatemapConfig,
    RatemapPack,
    build_default_xbin,
    build_ratemap_from_trials,
    normalize_x_to_100,
)
from .decoding import (
    BayesianDecoderConfig,
    BayesianDecodingResult,
    DecodeGroupBy,
    build_regular_xbin,
    decode_bayesian_position_from_trials,
)
from .population_geometry import (
    DisplacementProfile,
    PopulationGeometryConfig,
    PopulationGeometryGroupResult,
    PopulationGeometrySessionResult,
    ZoneDisplacementProfiles,
    build_population_geometry_for_group,
    build_population_geometry_from_saved_ratemap,
    compute_condition_component_displacement_profiles,
    compute_condition_zone_displacement_profiles,
    compute_displacement_profile,
    compute_normalization_scales,
    compute_zone_displacement_profiles,
    decode_condway,
    rebin_trial_maps,
)
from .trials import (
    TrialInfo,
    build_condway,
    build_trial_info_from_traj,
    canonical_condition_name,
    condition_family_name,
)

__all__ = [
    "ifreq_swap",
    "matlab_1b_to_python_0b",
    "gaussian_kernel_1d",
    "smooth_last_axis",
    "divide_with_nan",
    "SavedRatemapPack",
    "load_saved_ratemap_pack",
    "load_traj_condition_names",
    "subset_saved_ratemap_pack_cells",
    "load_cell_classification_table",
    "filter_cell_ids_by_pred_type",
    "CueZoneLayout",
    "complement_spans",
    "cue_zone_layout_for_condition",
    "label_xbin_centers_by_zone",
    "label_xbin_centers_by_zone_component",
    "zone_component_names_for_layout",
    "NullBootstrapConfig",
    "simulate_null_fr_s_txrep",
    "empirical_pval_tx",
    "empirical_pval_cx",
    "spatial_selectivity_index",
    "spatial_selectivity_index_reps",
    "compute_condition_occupancy",
    "ssi_observed_by_condition",
    "ssi_null_by_condition",
    "empirical_pvalue_from_null",
    "RatemapConfig",
    "RatemapPack",
    "BayesianDecoderConfig",
    "BayesianDecodingResult",
    "DecodeGroupBy",
    "DisplacementProfile",
    "PopulationGeometryConfig",
    "PopulationGeometryGroupResult",
    "PopulationGeometrySessionResult",
    "ZoneDisplacementProfiles",
    "TrialInfo",
    "normalize_x_to_100",
    "build_default_xbin",
    "build_regular_xbin",
    "build_condway",
    "build_trial_info_from_traj",
    "canonical_condition_name",
    "condition_family_name",
    "build_ratemap_from_trials",
    "decode_bayesian_position_from_trials",
    "decode_condway",
    "rebin_trial_maps",
    "compute_displacement_profile",
    "compute_zone_displacement_profiles",
    "compute_condition_component_displacement_profiles",
    "compute_condition_zone_displacement_profiles",
    "compute_normalization_scales",
    "build_population_geometry_for_group",
    "build_population_geometry_from_saved_ratemap",
]
