from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


def format_param_token(name: str, value: float | None) -> str:
    if value is None:
        return f"{name}_na"
    txt = f"{float(value):g}"
    txt = txt.replace("-", "m").replace(".", "p")
    return f"{name}_{txt}"


def build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(
        description=(
            "Plot one figure per condition for putative place cells selected by "
            "p_value < sm_alpha from ssi_classification.csv. "
            "Each figure contains mean ratemap, trial heatmap, SSI histogram, and occupancy."
        )
    )
    ap.add_argument(
        "--classification_csv",
        type=str,
        default="results/placefield_null/ssi_classification.csv",
        help="CSV produced by build_placefield_null_from_interim.py.",
    )
    ap.add_argument(
        "--pfnull_root",
        type=str,
        default="results/placefield_null",
        help="Root containing per-session *_pfnull.npz files generated by bootstrap script.",
    )
    ap.add_argument("--out_root", type=str, default="results/figures/putative_pcells")
    ap.add_argument(
        "--schedule_xlsx",
        type=str,
        default="data/schedule.xlsx",
        help="Excel file containing session age metadata (columns: SessionName, Age).",
    )
    ap.add_argument(
        "--schedule_sheet",
        type=str,
        default="VINCA",
        help="Excel sheet name used to load session age metadata.",
    )
    ap.add_argument(
        "--unknown_age_label",
        type=str,
        default="unmapped",
        help="Folder label to use when session age is missing in schedule metadata.",
    )
    ap.add_argument(
        "--sm_alpha",
        type=float,
        default=0.05,
        help="Putative place-cell threshold: select rows where p_value < sm_alpha.",
    )
    ap.add_argument(
        "--only_sm_conditions",
        action="store_true",
        help="If set, only plot condition(s) where p_value < sm_alpha for each selected cell.",
    )
    ap.add_argument("--dpi", type=int, default=140)
    ap.add_argument(
        "--hist_bins",
        type=int,
        default=40,
        help="Number of bins for SSI null histogram.",
    )
    ap.add_argument(
        "--heatmap_percentile",
        type=float,
        default=99.0,
        help="Upper percentile for heatmap color scaling.",
    )
    ap.add_argument(
        "--no_param_subdir",
        action="store_true",
        help="If set, do not append parameterized subdirectory to out_root.",
    )
    ap.add_argument("--overwrite", action="store_true")
    return ap


def _parse_meta_json(raw: np.ndarray) -> dict[str, Any]:
    try:
        txt = raw.tobytes().decode("utf-8", errors="ignore")
        obj = json.loads(txt)
        if isinstance(obj, dict):
            return obj
    except Exception:
        pass
    return {}


def _read_pfnull_meta(pfnull_path: Path) -> dict[str, Any]:
    with np.load(pfnull_path, allow_pickle=False) as z:
        if "meta_json" not in z.files:
            return {}
        return _parse_meta_json(z["meta_json"])


def _normalize_session_key(value: object) -> str:
    return " ".join(str(value).strip().split())


def _load_age_map(schedule_xlsx: Path, sheet_name: str) -> dict[str, int]:
    if not schedule_xlsx.exists():
        raise FileNotFoundError(f"Missing schedule file: {schedule_xlsx}")
    d = pd.read_excel(schedule_xlsx, sheet_name=sheet_name)
    required = {"SessionName", "Age"}
    missing = [c for c in required if c not in d.columns]
    if missing:
        raise KeyError(
            f"Missing required columns in {schedule_xlsx} [{sheet_name}]: {missing}"
        )
    d = d[["SessionName", "Age"]].copy()
    d["session_key"] = d["SessionName"].map(_normalize_session_key)
    d["Age"] = pd.to_numeric(d["Age"], errors="coerce")
    d = d.dropna(subset=["session_key", "Age"])
    d["age_int"] = d["Age"].astype(np.int64)
    d = d.drop_duplicates(subset=["session_key"], keep="first")
    return {
        str(k): int(v)
        for k, v in zip(d["session_key"].astype(str), d["age_int"].astype(np.int64))
    }


def find_pfnull_file(pfnull_root: Path, session_id: str) -> Path | None:
    cands = sorted(pfnull_root.rglob(f"{session_id}_pfnull.npz"))
    if not cands:
        return None
    if len(cands) > 1:
        print(f"WARN: multiple pfnull files for {session_id}; using {cands[-1]}")
    return cands[-1]


def load_pfnull_maps_for_cell(pfnull_path: Path, cell_id: int) -> dict[str, Any] | None:
    with np.load(pfnull_path, allow_pickle=False) as z:
        required = [
            "cell_ids",
            "idcond_t",
            "xbin_centers",
            "dwell_cx_x",
            "occupancy_cx",
            "pfnull__fr_tx_ux",
            "pfnull__fr_s_tx_ux",
            "pfnull__fr_cx_ux",
            "pfnull__fr_s_cx_ux",
        ]
        missing = [k for k in required if k not in z.files]
        if missing:
            raise KeyError(
                f"{pfnull_path} missing key(s): {missing}. "
                "Re-run build_placefield_null_from_interim.py with the updated version."
            )

        cell_ids = z["cell_ids"].astype(np.int64, copy=False)
        idx = np.where(cell_ids == int(cell_id))[0]
        if idx.size == 0:
            return None
        u = int(idx[0])

        out: dict[str, Any] = {
            "idcond_t": z["idcond_t"].astype(np.int64, copy=False),
            "xcent": z["xbin_centers"].astype(np.float64, copy=False),
            "dwell_cx": z["dwell_cx_x"].astype(np.float64, copy=False),
            "occupancy_cx": z["occupancy_cx"].astype(np.float64, copy=False),
            "fr_tx": z["pfnull__fr_tx_ux"][u].astype(np.float64, copy=False),
            "fr_s_tx": z["pfnull__fr_s_tx_ux"][u].astype(np.float64, copy=False),
            "fr_cx": z["pfnull__fr_cx_ux"][u].astype(np.float64, copy=False),
            "fr_s_cx": z["pfnull__fr_s_cx_ux"][u].astype(np.float64, copy=False),
            "meta": _parse_meta_json(z["meta_json"]) if "meta_json" in z.files else {},
        }
        if "pfnull__ssi_obs_cu" in z.files:
            out["ssi_obs_c"] = z["pfnull__ssi_obs_cu"][u].astype(np.float64, copy=False)
        if "pfnull__ssi_pval_cu" in z.files:
            out["ssi_pval_c"] = z["pfnull__ssi_pval_cu"][u].astype(np.float64, copy=False)
        if "pfnull__ssi_null_cur" in z.files:
            out["ssi_null_cr"] = z["pfnull__ssi_null_cur"][u].astype(np.float64, copy=False)
    return out


def main() -> None:
    args = build_parser().parse_args()
    if not (0.0 < float(args.sm_alpha) < 1.0):
        raise ValueError("--sm_alpha must be strictly between 0 and 1.")

    classification_csv = Path(args.classification_csv)
    pfnull_root = Path(args.pfnull_root)
    out_root_base = Path(args.out_root)
    schedule_xlsx = Path(args.schedule_xlsx)

    if not classification_csv.exists():
        raise FileNotFoundError(f"Missing classification CSV: {classification_csv}")
    if not pfnull_root.exists():
        raise FileNotFoundError(f"Missing pfnull root: {pfnull_root}")
    age_map = _load_age_map(schedule_xlsx, str(args.schedule_sheet))

    d = pd.read_csv(classification_csv)
    required_cols = ["session_id", "cell_id", "condition_1b", "p_value"]
    missing_cols = [c for c in required_cols if c not in d.columns]
    if missing_cols:
        raise KeyError(f"Missing required columns in {classification_csv}: {missing_cols}")

    d = d.copy()
    d["session_id"] = d["session_id"].astype(str)
    d["cell_id"] = pd.to_numeric(d["cell_id"], errors="coerce").astype("Int64")
    d["condition_1b"] = pd.to_numeric(d["condition_1b"], errors="coerce").astype("Int64")
    d["p_value"] = pd.to_numeric(d["p_value"], errors="coerce")
    d = d.dropna(subset=["session_id", "cell_id", "condition_1b"])
    d["cell_id"] = d["cell_id"].astype(np.int64)
    d["condition_1b"] = d["condition_1b"].astype(np.int64)
    d["is_sm_alpha"] = np.isfinite(d["p_value"]) & (d["p_value"] < float(args.sm_alpha))

    d_sm = d[d["is_sm_alpha"]].copy()
    if d_sm.empty:
        print(f"No rows with p_value < {float(args.sm_alpha):.6g}. Nothing to plot.")
        return

    units = (
        d_sm[["session_id", "cell_id"]]
        .drop_duplicates()
        .sort_values(["session_id", "cell_id"], kind="stable")
        .reset_index(drop=True)
    )

    # Infer smoothing parameter(s) from the actual pfnull files used for plotting.
    session_ids = units["session_id"].astype(str).drop_duplicates().tolist()
    session_pfnull: dict[str, Path] = {}
    smooth_vals: list[float] = []
    for sid in session_ids:
        p = find_pfnull_file(pfnull_root, sid)
        if p is None:
            continue
        session_pfnull[sid] = p
        meta = _read_pfnull_meta(p)
        sval = meta.get("smooth_sigma_bins")
        if sval is None:
            continue
        try:
            sf = float(sval)
            if np.isfinite(sf):
                smooth_vals.append(sf)
        except Exception:
            continue

    if smooth_vals:
        uniq_s = sorted(set(smooth_vals))
        if len(uniq_s) == 1:
            smooth_tag = format_param_token("smooth", uniq_s[0])
        else:
            smooth_tag = "smooth_mixed"
    else:
        smooth_tag = "smooth_unknown"

    if args.no_param_subdir:
        out_root = out_root_base
    else:
        run_tag = "__".join([smooth_tag, format_param_token("p", float(args.sm_alpha))])
        out_root = out_root_base / run_tag
    out_root.mkdir(parents=True, exist_ok=True)

    print(
        f"Putative place cells (unique session/cell, p_value < {float(args.sm_alpha):.6g}): {len(units)}"
    )
    print(f"Loaded age metadata for sessions: {len(age_map)}")
    print(f"Output root: {out_root}")

    idx_rows: list[dict[str, Any]] = []
    for i, row in units.iterrows():
        session_id = str(row["session_id"])
        cell_id = int(row["cell_id"])
        unit_rows = d[(d["session_id"] == session_id) & (d["cell_id"] == cell_id)].copy()
        unit_rows = unit_rows.sort_values("condition_1b", kind="stable")
        age = age_map.get(_normalize_session_key(session_id))
        age_label = str(int(age)) if age is not None else str(args.unknown_age_label)
        out_dir = out_root / age_label / session_id / f"cell_{cell_id}"
        out_dir.mkdir(parents=True, exist_ok=True)

        pfnull_path = session_pfnull.get(session_id)
        if pfnull_path is None:
            print(f"WARN [{i+1}/{len(units)}]: pfnull missing for {session_id}")
            idx_rows.append(
                {
                    "session_id": session_id,
                    "cell_id": cell_id,
                    "status": "missing_pfnull",
                }
            )
            continue

        try:
            loaded = load_pfnull_maps_for_cell(pfnull_path, cell_id)
            if loaded is None:
                print(f"WARN [{i+1}/{len(units)}]: cell {cell_id} not found in {pfnull_path.name}")
                idx_rows.append(
                    {
                        "session_id": session_id,
                        "cell_id": cell_id,
                        "status": "cell_not_in_pfnull",
                        "pfnull_npz": str(pfnull_path),
                    }
                )
                continue

            idcond_t = loaded["idcond_t"]
            xcent = loaded["xcent"]
            dwell_cx = loaded["dwell_cx"]
            occupancy_cx = loaded["occupancy_cx"]
            fr_tx = loaded["fr_tx"]
            fr_s_tx = loaded["fr_s_tx"]
            fr_cx = loaded["fr_cx"]
            fr_s_cx = loaded["fr_s_cx"]
            meta = loaded.get("meta", {})
            ssi_obs_c = loaded.get("ssi_obs_c")
            ssi_pval_c = loaded.get("ssi_pval_c")
            ssi_null_cr = loaded.get("ssi_null_cr")

            n_cond = int(
                min(
                    fr_cx.shape[0],
                    fr_s_cx.shape[0],
                    dwell_cx.shape[0],
                    occupancy_cx.shape[0],
                )
            )
            if n_cond <= 0:
                raise ValueError("No conditions available in pfnull arrays.")
            if args.only_sm_conditions:
                cond_keep = sorted(
                    {
                        int(c - 1)
                        for c in unit_rows.loc[unit_rows["is_sm_alpha"], "condition_1b"].tolist()
                        if 1 <= int(c) <= n_cond
                    }
                )
            else:
                cond_keep = list(range(n_cond))

            if not cond_keep:
                idx_rows.append(
                    {
                        "session_id": session_id,
                        "cell_id": cell_id,
                        "status": "no_conditions_selected",
                        "pfnull_npz": str(pfnull_path),
                    }
                )
                continue

            smooth_meta = meta.get("smooth_sigma_bins")
            xrem_meta = meta.get("xbin_rem")
            for c0 in cond_keep:
                cond1b = int(c0 + 1)
                out_png = out_dir / f"cond_{cond1b}.png"
                if out_png.exists() and not args.overwrite:
                    print(
                        f"SKIP [{i+1}/{len(units)}]: age {age_label} | {session_id} cell {cell_id} cond {cond1b} (figure exists)"
                    )
                    idx_rows.append(
                        {
                            "age": age_label,
                            "session_id": session_id,
                            "cell_id": cell_id,
                            "condition_1b": cond1b,
                            "status": "skip_exists",
                            "pfnull_npz": str(pfnull_path),
                            "figure_png": str(out_png),
                        }
                    )
                    continue

                row_c = unit_rows[unit_rows["condition_1b"] == cond1b]
                pval_csv = float("nan") if row_c.empty else float(row_c["p_value"].iloc[0])
                pval = pval_csv
                if (ssi_pval_c is not None) and (c0 < int(ssi_pval_c.shape[0])):
                    pval = float(ssi_pval_c[c0])
                sm = bool(np.isfinite(pval) and (pval < float(args.sm_alpha)))
                ptxt = f"p={pval:.3g}" if np.isfinite(pval) else "p=NA"
                smtxt = f"SM@{float(args.sm_alpha):.3g}={sm}"

                ssi_obs = float("nan")
                if (ssi_obs_c is not None) and (c0 < int(ssi_obs_c.shape[0])):
                    ssi_obs = float(ssi_obs_c[c0])
                elif "ssi_obs" in row_c.columns and not row_c.empty:
                    ssi_obs = float(row_c["ssi_obs"].iloc[0])

                y_raw = fr_cx[c0]
                y_sm = fr_s_cx[c0]
                y_stack = np.concatenate([y_raw.ravel(), y_sm.ravel()])
                y_stack = y_stack[np.isfinite(y_stack)]
                y_upper = float(np.max(y_stack)) if y_stack.size else 1.0
                if not np.isfinite(y_upper) or y_upper <= 0:
                    y_upper = 1.0

                fig, axes = plt.subplots(2, 2, figsize=(12.5, 8.8), squeeze=False)
                ax_mean = axes[0, 0]
                ax_hist = axes[0, 1]
                ax_heat = axes[1, 0]
                ax_occ = axes[1, 1]

                # Panel 1: condition mean ratemap.
                ax_mean.plot(xcent, y_raw, color="0.65", linewidth=1.6, label="mean unsmoothed")
                ax_mean.plot(xcent, y_sm, color="#1f77b4", linewidth=2.0, label="mean smoothed")
                ax_mean.set_title(f"Condition {cond1b} Mean Ratemap | {ptxt} | {smtxt}", fontsize=10)
                ax_mean.set_xlabel("Position")
                ax_mean.set_ylabel("Rate")
                ax_mean.set_ylim(bottom=0.0, top=y_upper * 1.05)
                ax_mean.grid(alpha=0.25)
                ax_mean.legend(loc="best", fontsize=8)

                # Panel 2: null SSI histogram for this condition.
                null_ok = False
                if (ssi_null_cr is not None) and (c0 < int(ssi_null_cr.shape[0])):
                    ssi_null = np.asarray(ssi_null_cr[c0], dtype=np.float64).ravel()
                    ssi_null = ssi_null[np.isfinite(ssi_null)]
                    if ssi_null.size > 0:
                        null_ok = True
                        ax_hist.hist(
                            ssi_null,
                            bins=max(5, int(args.hist_bins)),
                            color="#9ecae1",
                            edgecolor="#4a6fa5",
                            linewidth=0.8,
                        )
                        if np.isfinite(ssi_obs):
                            ax_hist.axvline(
                                float(ssi_obs),
                                color="#d62728",
                                linestyle="--",
                                linewidth=2.0,
                                label="Observed SSI",
                            )
                        ax_hist.legend(loc="best", fontsize=8)
                if not null_ok:
                    ax_hist.text(
                        0.5,
                        0.5,
                        "SSI null distribution not saved.\nRerun bootstrap with --save_ssi_null.",
                        ha="center",
                        va="center",
                        transform=ax_hist.transAxes,
                    )
                ax_hist.set_title(f"Condition {cond1b} SSI Null Histogram", fontsize=10)
                ax_hist.set_xlabel("SSI")
                ax_hist.set_ylabel("Count")
                ax_hist.grid(alpha=0.2)

                # Panel 3: trial-by-trial heatmap (smoothed trial maps).
                idx_cond = np.where(idcond_t.astype(np.int64, copy=False) == cond1b)[0]
                if idx_cond.size == 0:
                    ax_heat.text(
                        0.5,
                        0.5,
                        "No trials for this condition",
                        ha="center",
                        va="center",
                        transform=ax_heat.transAxes,
                    )
                    ax_heat.set_axis_off()
                else:
                    heat = fr_s_tx[idx_cond, :]
                    heat_fin = heat[np.isfinite(heat)]
                    vmax = np.nan
                    if heat_fin.size:
                        vmax = float(np.nanpercentile(heat_fin, float(args.heatmap_percentile)))
                    if not np.isfinite(vmax) or vmax <= 0:
                        vmax = float(np.nanmax(heat_fin)) if heat_fin.size else 1.0
                    if not np.isfinite(vmax) or vmax <= 0:
                        vmax = 1.0
                    im = ax_heat.imshow(
                        heat,
                        aspect="auto",
                        origin="lower",
                        interpolation="nearest",
                        extent=[float(xcent[0]), float(xcent[-1]), 1, int(idx_cond.size)],
                        vmin=0.0,
                        vmax=float(vmax),
                        cmap="viridis",
                    )
                    ax_heat.set_title(
                        f"Condition {cond1b} Trial Heatmap (Smoothed) | n_trials={int(idx_cond.size)}",
                        fontsize=10,
                    )
                    ax_heat.set_xlabel("Position")
                    ax_heat.set_ylabel("Trial (within condition)")
                    cbar = fig.colorbar(im, ax=ax_heat, fraction=0.046, pad=0.04)
                    cbar.set_label("Rate")

                # Panel 4: occupancy and dwell time by bin for this condition.
                dwell_cond = np.asarray(dwell_cx[c0], dtype=np.float64)
                occ_cond = np.asarray(occupancy_cx[c0], dtype=np.float64)
                bw = 1.0
                if xcent.size >= 2:
                    dx = np.diff(xcent)
                    dx = dx[np.isfinite(dx)]
                    if dx.size:
                        bw = float(np.median(dx))
                ax_occ.bar(
                    xcent,
                    np.nan_to_num(dwell_cond, nan=0.0),
                    width=float(max(0.1, bw * 0.9)),
                    color="0.82",
                    edgecolor="0.6",
                    linewidth=0.3,
                    label="Dwell (s)",
                )
                ax_occ.set_xlabel("Position")
                ax_occ.set_ylabel("Dwell Time (s)")
                ax_occ.set_ylim(bottom=0.0)
                ax_occ.grid(alpha=0.2, axis="y")
                ax_occ2 = ax_occ.twinx()
                ax_occ2.plot(
                    xcent,
                    np.nan_to_num(occ_cond, nan=0.0),
                    color="#2ca02c",
                    linewidth=1.8,
                    label="Normalized occupancy",
                )
                ax_occ2.set_ylabel("Occupancy (norm)")
                ax_occ2.set_ylim(bottom=0.0)
                h1, l1 = ax_occ.get_legend_handles_labels()
                h2, l2 = ax_occ2.get_legend_handles_labels()
                ax_occ.legend(h1 + h2, l1 + l2, loc="best", fontsize=8)
                ax_occ.set_title(f"Condition {cond1b} Occupancy", fontsize=10)

                fig.suptitle(
                        (
                            f"age={age_label} | {session_id} | cell {cell_id} | cond {cond1b} | "
                            f"{ptxt} | {smtxt} | smooth={smooth_meta} | xbin_rem={xrem_meta}"
                        ),
                        y=1.01,
                    )
                fig.tight_layout()
                fig.savefig(out_png, dpi=int(args.dpi), bbox_inches="tight")
                plt.close(fig)

                print(
                    f"OK   [{i+1}/{len(units)}]: age {age_label} | {session_id} cell {cell_id} cond {cond1b} -> {out_png}"
                )
                idx_rows.append(
                    {
                        "age": age_label,
                        "session_id": session_id,
                        "cell_id": cell_id,
                        "condition_1b": cond1b,
                        "status": "ok",
                        "pfnull_npz": str(pfnull_path),
                        "figure_png": str(out_png),
                        "n_trials_in_condition": int(idx_cond.size),
                        "sm_alpha": float(args.sm_alpha),
                        "p_value": pval,
                        "SM": sm,
                        "ssi_obs": ssi_obs,
                        "has_ssi_null": bool(null_ok),
                        "smooth_sigma_bins_meta": smooth_meta,
                    }
                )
        except Exception as exc:
            print(f"FAIL [{i+1}/{len(units)}]: {session_id} cell {cell_id} -> {exc}")
            idx_rows.append(
                {
                    "age": age_label,
                    "session_id": session_id,
                    "cell_id": cell_id,
                    "status": "error",
                    "pfnull_npz": str(pfnull_path),
                    "error": str(exc),
                }
            )

    index_path = out_root / "plot_index.csv"
    pd.DataFrame(idx_rows).to_csv(index_path, index=False)
    print(f"Wrote plot index: {index_path}")
    print("Done.")


if __name__ == "__main__":
    main()
